### ISSUE TITLE
Dead links for remixed kirigami STLs

### ISSUE THREAD

**Issue by manisto** [SrgntBallistic/Formbot-V0#2]
I'm sorry for creating an issue for this, but I didn't know how else to contact you. The links for the remixed STLs for the kirigami bed on Printables are dead. I'm having the same issue as you, with the Z axis nut block fitting too tight, making the frame flex just enough that it doesn't run smoothly. If you have a local copy of those STLs, I would be very happy if you would add them to the `stl` folder of this repo.

**Comment by SrgntBallistic** [comment]
Thanks for *bringing this to my attention.

I'll look at the links. Putting them in the STLs folder is tough because they can get out of date if the original creator updates them.

But in this case it might be ok.

*Edit: Typo

**Comment by SrgntBallistic** [comment]
Looks like the model creator removed the files from Printables. I don't know why. I will see if I have them downloaded on a computer and upload them here.

If I can't find them I will try to recreate them

**Comment by manisto** [comment]
All right, so I decided to take up the challenge and modify the STEP file for the nut block myself. I've made a parametric model, and am currently printing four variations. They should each accommodate a thickness of the frame for 2.1mm, 2.2mm, 2.3mm and 2.4mm, respectively. If they do the trick, I will upload them to Printables.

**Comment by SrgntBallistic** [comment]
@manisto lmk if you get them uploaded! I'll do a test print and provide any feedback I can on my extra formbot bed frame. And replace the existing links/credit on GH!

Thanks

**Comment by manisto** [comment]
There, uploaded the remix: https://www.printables.com/model/837960-kirigami-bed-nut-block-for-voron-v02

The .2 version worked perfectly for me. Thank you for your awesome and very comprehensive build guide.

*Edit fixed typo

**Comment by SrgntBallistic** [comment]
@manisto I updated the readme and included a link to your model. I rated it and uploaded a make. Thanks for the contributions
